version: '3.8'

networks:
  intranet:
    driver: bridge

services:
  kurento-media-server:
    build:
      context: ./kurento
      dockerfile: Dockerfile
    container_name: kurento-media-server
    ports:
      - "8888:8888"
    environment:
      # - GST_DEBUG=3
      - KMS_USE_GPU=false  # Disable GPU acceleration
      - GST_VAAPI_ALL_DRIVERS=1
      - GST_DEBUG=cuda*:0
    networks:
      - intranet
    restart: always
    volumes:
      - ./kurento/config/kurento.conf.json:/etc/kurento/kurento.conf.json

  node-server:
    image: node:20-alpine3.20
    container_name: node-server
    working_dir: /app
    volumes:
      - ./server:/app/server
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./public:/app/public
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && node server/index.js"
    depends_on:
      - kurento-media-server
    networks:
      - intranet
